#include<iostream.h>
#include<conio.h>
#include<process.h>

void main () {
	clrscr();
	int choice, loop;

	do {
		clrscr();
		cout << "Main menu\n";
		cout << "1- Print 10 times\n";
		cout << "2- 1 to 5\n" ;
		cout << "3- 5 to 1\n";
		cout << "4- even 5 to 1\n";
		cout << "5- odd 5 to 1\n";
		cout << "6- Prime or not\n";
		cout << "7- Factorial\n";
		cout << "8- GCD\n";
		cout << "0 - exit\n";
		cout << "choice: ";	
		cin >> choice;

		switch (choice) {
			case 1:
				do {
					clrscr();
					cout << "CASE 1 Sub menu loop\n";
					cout << "1- for\n";
					cout << "2- dow\n";
					cout << "3 - while\n";
					cout << "0 - exit\n";
					cout << "choose loop: ";
					cin >> loop;

					switch (loop) {
						case 1:
							clrscr();
							cout << "using loop";
							getch();
							break;
						case 2:
							clrscr();
							cout << "using do while";
							getch();
							break;
						case 3:
							clrscr();
							cout << "using while";
							getch();
							break;
						case 0:
							exit(0);
							break;
					default:
						clrscr();
						cout << "Invalid loop. Choose only from 1 to 3 choices.";
						getch();
						break;
					}
				}
				while (loop != 0);

			case 2:
				do {
					clrscr();
					cout << "CASE 2 Sub menu loop\n";
					cout << "1- for\n";
					cout << "2- dow\n";
					cout << "3 - while\n";
					cout << "0 - exit\n";
					cout << "choose loop: ";
					cin >> loop;	

					switch (loop) {
						case 1:
							clrscr();
							cout << "using loop";
							getch();
							break;
						case 2:
							clrscr();
							cout << "using do while";
							getch();
							break;
						case 3:
							clrscr();
							cout << "using while";
							getch();
							break;
						case 0:
							exit(0);
							break;
					default:
						clrscr();
						cout << "Invalid loop. Choose only from 1 to 3 choices.";
						getch();
						break;
					}
				}
				while (loop != 0 );
			case 3:
				do {
					clrscr();
					cout << "CASE 3 Sub menu loop\n";
					cout << "1- for\n";
					cout << "2- dow\n";
					cout << "3 - while\n";
					cout << "0 - exit\n";
					cout << "choose loop: ";
					cin >> loop;

					switch (loop) {
						case 1:
							clrscr();
							cout << "using loop";
							getch();
							break;
						case 2:
							clrscr();
							cout << "using do while";
							getch();
							break;
						case 3:
							clrscr();
							cout << "using while";
							getch();
							break;
						case 0:
							exit(0);
							break;
					default:
						clrscr();
						cout << "Invalid loop. Choose only from 1 to 3 choices.";
						getch();
						break;
					}
				}
				while (loop != 0 );
			case 4:
				do {
					clrscr();
					cout << "CASE 4 Sub menu loop\n";
					cout << "1- for\n";
					cout << "2- dow\n";
					cout << "3 - while\n";
					cout << "0 - exit\n";
					cout << "choose loop: ";
					cin >> loop;

					switch (loop) {
						case 1:
							clrscr();
							cout << "using loop";
							getch();	
							break;
						case 2:
							clrscr();
							cout << "using do while";
							getch();		
							break;
						case 3:
							clrscr();
							cout << "using while";
							getch();
							break;
						case 0:
							exit(0);
							break;
					default:
						clrscr();
						cout << "Invalid loop. Choose only from 1 to 3 choices.";
						getch();
						break;
					}
				}
				while (loop != 0 );
			case 5:
				do {
					clrscr();
					cout << "CASE 5 Sub menu loop\n";
					cout << "1- for\n";
					cout << "2- dow\n";
					cout << "3 - while\n";
					cout << "0 - exit\n";
					cout << "choose loop: ";
					cin >> loop;

					switch (loop) {
						case 1:
							clrscr();
							cout << "using loop";
							getch();
							break;
						case 2:
							clrscr();
							cout << "using do while";
							getch();
							break;
						case 3:
							clrscr();
							cout << "using while";
							getch();
							break;
						case 0:
							exit(0);
							break;
					default:
						clrscr();
						cout << "Invalid loop. Choose only from 1 to 3 choices.";
						getch();
						break;
					}
				}
				while (loop != 0 );

			case 6:
				do {	
					clrscr();
					cout << "CASE 6 Sub menu loop\n";
					cout << "1- for\n";
					cout << "2- dow\n";
					cout << "3 - while\n";
					cout << "0 - exit\n";
					cout << "choose loop: ";
					cin >> loop;

					switch (loop) {
						case 1:
							clrscr();
							cout << "using loop";
							getch();
							break;
						case 2:
							clrscr();
							cout << "using do while";
							getch();
							break;
						case 3:
							clrscr();
							cout << "using while";
							getch();
							break;
						case 0:
							exit(0);
							break;
					default:
						clrscr();
						cout << "Invalid loop. Choose only from 1 to 3 choices.";
						getch();
						break;
					}
				}
				while (loop != 0 );
			case 7:
				do {
					clrscr();
					cout << "CASE 7 Sub menu loop\n";
					cout << "1- for\n";
					cout << "2- dow\n";
					cout << "3 - while\n";
					cout << "0 - exit\n";
					cout << "choose loop: ";
					cin >> loop;

					switch (loop) {
						case 1:
							clrscr();
							cout << "using loop";
							getch();
							break;
						case 2:
							clrscr();
							cout << "using do while";
							getch();
							break;
						case 3:
							clrscr();
							cout << "using while";
							getch();
							break;
						case 0:
							exit(0);
							break;
					default:
						clrscr();
						cout << "Invalid loop. Choose only from 1 to 3 choices.";
						getch();
						break;
					}
				}
				while (loop != 0 );
			case 8:
				do {
					clrscr();
					cout << "CASE 8 Sub menu loop\n";
					cout << "1- for\n";
					cout << "2- dow\n";
					cout << "3 - while\n";
					cout << "0 - exit\n";
					cout << "choose loop: ";
					cin >> loop;

					switch (loop) {
						case 1:
							clrscr();
							cout << "using loop";
							getch();
							break;
						case 2:
							clrscr();
							cout << "using do while";
							getch();
							break;
						case 3:
							clrscr();
							cout << "using while";
							getch();
							break;
						case 0:
							exit(0);
							break;
					default:
						clrscr();
						cout << "Invalid loop. Choose only from 1 to 3 choices.";
						getch();
						break;
					}
				}
				while (loop != 0 );
			case 0: exit(0);
		default:
			clrscr();
			cout << "Invalid choice. Choose only from the loop menu.";
			getch();
			break;	
		}
	}
	while (choice != 10);

getch();
}