#include<iostream.h>
#include<conio.h>

void main()
{
	clrscr();

	gotoxy(27,9);
	cout << "Grace Gabrielle P. Banzali" << endl;
	gotoxy(27,10);
	cout << "Grace Gabrielle P. Banzali" << endl;
	gotoxy(27,11);
	cout << "Grace Gabrielle P. Banzali" << endl;
	gotoxy(27,12);
	cout << "Grace Gabrielle P. Banzali" << endl;
	gotoxy(27,13);
	cout << "Grace Gabrielle P. Banzali" << endl;



	getch();
}