#include<iostream.h>
#include<conio.h>

void main()
{
	clrscr();

	gotoxy(35,12);
	textcolor(1+128);
		cprintf("H");
	gotoxy(36,12);
	textcolor(2+128);
		cprintf("E");
	gotoxy(37,12);
	textcolor(5+128);
		cprintf("L");
	gotoxy(38,12);
	textcolor(8+128);
		cprintf("L");
	gotoxy(39,12);
	textcolor(6+128);
		cprintf("O");

	gotoxy(41,12);
	textcolor(3+128);
		cprintf("W");
	gotoxy(42,12);
	textcolor(4+128);
		cprintf("O");
	gotoxy(43,12);
	textcolor(9+128);
		cprintf("R");
	gotoxy(44,12);
	textcolor(14+128);
		cprintf("L");
	gotoxy(45,12);
	textcolor(10+128);
		cprintf("D");
	gotoxy(46,12);
	textcolor(12+128);
		cprintf("!");

	gotoxy(38,13);
	textcolor(2+128);
		cprintf ("Gabby");

	getch();

}